### ISSUE TITLE
Performance comparison

### ISSUE THREAD

**Issue by erotavlas85** [rocketshipapps/adblockfast#63]
Hi,
in your Web site, you claims that adblockfast is the most efficient adblocker compared to adblock and adblock plus.
What about comparing it against [ublock origin](https://github.com/gorhill/uBlock) which is considered the most efficient adblocker?
Thank you

**Comment by oldestlivingboy** [comment]
You’re welcome to do the comparing<em>!</em> Our methodology is documented [here](../../adblockfast#benchmark-notes) and [on our site](https://adblockfast.com/#benchmark-notes).

**Comment by remusao** [comment]
@erotavlas85 I'm the maintainer for https://github.com/cliqz-oss/adblocker and I've added AdblockFast into a benchmark we try to keep up-to-date. There is also a version of uBlock Origin measured here. In short, content blockers nowadays are ridiculously efficient and on desktop the different between AdblockFast and a full-fledged blocker is very small (we're talking about a **0.002 ms** difference per request when it comes to deciding what to block). More here: https://github.com/cliqz-oss/adblocker/pull/133

I still need to re-run all the benchmarks in a controlled environment to update the results of everyone (will do that soon). But the figures in the PR description already give a good idea of what to expect.

**Comment by erotavlas85** [comment]
@remusao thank you for your reply. I will take a look at it. What about the performance in term of used RAM?

**Comment by remusao** [comment]
@erotavlas85 When I update the benchmark there will also be measurements of RAM used. But to be clear, an efficient adblocker will use 3-10MB with Easylist (of course it grows depending on how many rules you enable; numbers are for Cliqz or uBlock Origin, as other extensions might use more for the same filters). I expect `AdblockFast` to be lower (we will see from the measurements) but in the end it's a trade-off. I'm not convinced that lots of breakages and ads not blocked is worth it if it's to save 1-5MB of RAM used. Especially considering that:

1. Browsers are using few orders of magnitude more (few hundreds of MBs usually)
2. So are web pages (Not uncommon to see a page eating 10-100MB+)
3. Blocking ads will likely save more memory in pages than the weight of the adblocker itself anyway, so it's a net positive

**Comment by erotavlas85** [comment]
@remusao I partially agree with you. You are right that the most consuming RAM things are not add ons. However, consider that an add on could use 5-10 MB of RAM and you should multiple it for 30 add ons.
For this reason a benchmark for CPU and RAM is very useful.

**Comment by remusao** [comment]
@erotavlas85 I agree that measurements are important. I was just trying to give a perspective as to which trade-off you need to consent to in the case of AdblockFast. Also, while many extensions will increase the memory usage of your browser, I would expect adblockers to be the ones needing most memory to do their job, because of the complexity of what they are doing.

I've been running [the benchmarks](https://github.com/cliqz-oss/adblocker/tree/master/bench/comparison) again and as expected: the memory usage of AdblockFast is very low compared to adblockers (1-2 KB of RAM compared to 1-2MB, so three orders of magnitude less), but matching speed is basically the same (we're talking about ~0.010 milliseconds per request to decide if it should be blocked or not).

**Comment by oldestlivingboy** [comment]
Thanks for adding<em>!</em>
