### ISSUE TITLE
What exactly is "faster" doing?! 

### ISSUE THREAD

**Issue by mxxcon** [rocketshipapps/adblockfast#94]
On https://github.com/rocketshipapps/adblockfast/tree/main#how-do-adblock-fasts-mobile-blocking-modes-work you state

>  If you tap the Faster button or link, a more comprehensive, up-to-date set of filtering rules are activated; Faster is an experimental mode that uses what should be an **unnoticeable amount of your background bandwidth to crawl websites** and detect new ad domain names to filter (code for the latter will be open-sourced here once sufficiently cleaned up).

What is that supposed to mean?!
Are you using my phone to go to websites without my permission or telling me what websites it visits?! 
This sounds like a straight up malware botnet!

Also, this was never disclosed in the changelog
![Screenshot_20240404_022357_App Watcher](https://github.com/rocketshipapps/adblockfast/assets/847140/0fb7a89d-f275-4cc9-8e24-e5f59ddfabf3)

**Comment by oldestlivingboy** [comment]
Faster mode is intended to be **100% opt-in** for those who want more up-to-date blocking rules than we can cobble together (mostly) by hand and does what the onboarding dialog and FAQ say (I’m not sure how you found yourself in this mode after an update unless you switched modes via the second dialog below, which [we clarified in version 2.4.0](https://github.com/rocketshipapps/adblockfast/commit/f0f7dede12780c0c8c5622bfe8d206aa66c15615) in case of this user flow, or due to a bug):

![Onboarding dialog](https://github.com/rocketshipapps/adblockfast/assets/694490/035bd027-a1fd-40f1-8e28-1d94fcbe70f2)

You can switch modes by tapping the **About** button then either mode link:

![About dialog](https://github.com/rocketshipapps/adblockfast/assets/694490/45dbb825-9ba1-4d81-8f86-9e83c26fe1f3)

The mode options were published in [version 2.2.2](https://github.com/rocketshipapps/adblockfast/releases/tag/a2.2.2) not 2.3.0.

**Comment by mxxcon** [comment]
> what the onboarding dialog and FAQ say

There was no onboarding dialog AT ALL and I do not see any FAQ anywhere. The app updated and I saw that suddenly and without any warnings it was running in the background, so I started looking around all over the app and saw this fast and "faster" mode.

> The mode options were published in [version 2.2.2](https://github.com/rocketshipapps/adblockfast/releases/tag/a2.2.2) not 2.3.0.

As you can see my posted screenshot above, I did not get version 2.2.2. I had version 2.1.0 since Oct 2023 and then a few days ago I got 2.3.0. My phone checks for updates on daily basis. Looking at APKMirror they do not list 2.2.2 as released either.

You still have no explained what exactly this crawling will be doing with my phone.

**Comment by oldestlivingboy** [comment]
Did you tap the **Faster** link after updating<em>?</em> As mentioned, it’s possible there’s a bug (but I just reviewed the code and can’t find any way to bypass opting in).

**Comment by mxxcon** [comment]
I did not tap on it. I started looking around trying to figure out what it does.
I'm on version 2.3.0. There's nothing newer version available to me.

**Comment by oldestlivingboy** [comment]
We tracked the bug down; I guess the good news is that the bug is cosmetic only – nothing runs in the background unless you’ve explicitly opted in to Faster mode, but we may accidentally prompt you with the background notification even if you haven’t opted in.

I’m planning to submit a fix today (which will probably be published as version 2.4.0 on Play) and will leave this issue open till I do; thank you for your help in ID’ing the bug<em>!</em>

**Comment by oldestlivingboy** [comment]
Closed by https://github.com/rocketshipapps/adblockfast/releases/tag/a2.4.0.
